[project]
name = "altair-lab-rgallardo-chicago"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.4.1",
    "jupyter>=1.1.1",
    "pandas>=2.2.3",
    "polars>=1.9.0",
    "typing-extensions>=4.12.2",
]
